### ISSUE TITLE
LUIS ROS node crashes after a while

### ISSUE THREAD

**Issue by ghost** [ms-iot/ros_msft_luis#25]
The ROS node starts as expected, however after a while it crashes with the following errors

`Exception has occurred: W32/0xC0000409

Unhandled exception at 0x00007FF948C51208 (ucrtbase.dll) in ros_msft_luis_node.exe: An invalid parameter was passed to a function that considers invalid parameters fatal.
`
Most probably on this line
`float value = atof(json_object_dotget_string(resolution_object, "value"));`

This is the call stack at that point in time

`
    [Waiting on lock owned by Thread 19372] (Unknown Source:0)
ucrtbase.dll!00007ff948c51208() (Unknown Source:0)
ucrtbase.dll!00007ff948c024b1() (Unknown Source:0)
ucrtbase.dll!00007ff948c02379() (Unknown Source:0)
ucrtbase.dll!00007ff948c2e81e() (Unknown Source:0)
ros_msft_luis_node.exe!parseAndPublishFromJson(std::basic_string<char,std::char_traits<char>,std::allocator<char> > luisJson) Line 115 (c:\WS\catkin_ws\src\ros_msft_luis\src\azure_cs_luis.cpp:115)
ros_msft_luis_node.exe!`main'::`95'::<lambda_2>::operator()(const Microsoft::CognitiveServices::Speech::Intent::IntentRecognitionEventArgs & e) Line 279 (c:\WS\catkin_ws\src\ros_msft_luis\src\azure_cs_luis.cpp:279)
ros_msft_luis_node.exe!std::_Func_impl_no_alloc<`main'::`95'::<lambda_2>,void,Microsoft::CognitiveServices::Speech::Intent::IntentRecognitionEventArgs const &>::_Do_call(const Microsoft::CognitiveServices::Speech::Intent::IntentRecognitionEventArgs & <_Args_0>) Line 948 (c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\functional:948)
ros_msft_luis_node.exe!std::_Func_class<void,Microsoft::CognitiveServices::Speech::Intent::IntentRecognitionEventArgs const &>::operator()(const Microsoft::CognitiveServices::Speech::Intent::IntentRecognitionEventArgs & <_Args_0>) Line 996 (c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\functional:996)
ros_msft_luis_node.exe!Microsoft::CognitiveServices::Speech::EventSignal<Microsoft::CognitiveServices::Speech::Intent::IntentRecognitionEventArgs const &>::Signal(const Microsoft::CognitiveServices::Speech::Intent::IntentRecognitionEventArgs & t) Line 207 (c:\WS\catkin_ws\build\ros_msft_luis\Microsoft.CognitiveServices.Speech.1.13.0\build\native\include\cxx_api\speechapi_cxx_eventsignal.h:207)
ros_msft_luis_node.exe!Microsoft::CognitiveServices::Speech::AsyncRecognizer<Microsoft::CognitiveServices::Speech::Intent::IntentRecognitionResult,Microsoft::CognitiveServices::Speech::Intent::IntentRecognitionEventArgs,Microsoft::CognitiveServices::Speech::Intent::IntentRecognitionCanceledEventArgs>::FireEvent_Recognized(_spx_empty * hreco, _spx_empty * hevent, void * pvContext) Line 401 (c:\WS\catkin_ws\build\ros_msft_luis\Microsoft.CognitiveServices.Speech.1.13.0\build\native\include\cxx_api\speechapi_cxx_recognition_async_recognizer.h:401)
Microsoft.CognitiveServices.Speech.core.dll!00007ff8aba8a4f4() (Unknown Source:0)
Microsoft.CognitiveServices.Speech.core.dll!00007ff8abb0f8cb() (Unknown Source:0)
Microsoft.CognitiveServices.Speech.core.dll!00007ff8abb169d7() (Unknown Source:0)
Microsoft.CognitiveServices.Speech.core.dll!00007ff8abb68106() (Unknown Source:0)
Microsoft.CognitiveServices.Speech.core.dll!00007ff8abb68399() (Unknown Source:0)
Microsoft.CognitiveServices.Speech.core.dll!00007ff8abb3f50c() (Unknown Source:0)
Microsoft.CognitiveServices.Speech.core.dll!00007ff8abb4fdb0() (Unknown Source:0)
Microsoft.CognitiveServices.Speech.core.dll!00007ff8abb4df96() (Unknown Source:0)
Microsoft.CognitiveServices.Speech.core.dll!00007ff8abb61895() (Unknown Source:0)

**Comment by tomconte** [comment]
Hi, together with my crew we are looking at tackling some issues from the backlog, and thought we would look at this one within our first batch.

I tried running the node on an Ubuntu machine, and let it run for a while, but did not see any crashes. Do you have some details that would help us reproduce?

Our first thought was to update the node to the latest version of the Speech SDK to see if it could help.

/cc @ooeygui
